### PR TITLE
bump build

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Tries a simple rebuild, without rerendering, to see if this is even green.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by akrherz** [comment]
appveyor failed without the rerender...

**Comment by akrherz** [comment]
@ocefpaf the build will fail after the rerender too.  I only bumped the version toward the end of my thrashing about.

**Comment by ocefpaf** [comment]
> appveyor failed without the rerender...

AppVeyor should not even be there :-), that is how old this feedstock is.

> @ocefpaf the build will fail after the rerender too. I only bumped the version toward the end of my thrashing about.

Let's wait for this one so we can have logs to inspect. wgrib is kind if hard to build :-/

**Comment by akrherz** [comment]
The current build logs in #2 pretty much will match what will happen here, actual code change associated with the wgrib version change was trivial

**Comment by akrherz** [comment]
Got things resolved in #2

**Pull request closed without merging**
