### PR TITLE
add akrherz as maintainer, bump build

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Lets see what happens here :)

@conda-forge-admin, please rerender

refs conda-forge/wgrib2-feedstock#24

### CODE REVIEW

**Comment by akrherz** [comment]
@conda-forge-admin, please rerender

**Comment by akrherz** [comment]
@conda-forge-admin, please rerender

**Comment by akrherz** [comment]
@conda-forge-admin, please rerender

**Comment by akrherz** [comment]
@ocefpaf I'm at a loss as to why this isn't working?  Any ideas?

**Comment by ocefpaf** [comment]
No idea. We should try to build the old version first just to check if it is changes in our compilers, etc or if it is the new version.

**Comment by akrherz** [comment]
holy cow @ocefpaf , amazing.  We'll still have windows troubles though :(

**Comment by ocefpaf** [comment]
> holy cow @ocefpaf , amazing.

Had to build it locally, unpack the broken package, and see that we had a `bin` file instead of a directory :-/

> We'll still have windows troubles though :(

We may need to restore the mingw-c compiler. I'm not sure...

**Comment by akrherz** [comment]
with mingw-c we get
```
2022-12-19T18:36:32.0707638Z wgrib_main.c: In function 'main':
2022-12-19T18:36:32.0708945Z wgrib_main.c:505:5: internal compiler error: Segmentation fault
2022-12-19T18:36:32.0709805Z      0.001*GDS_LatLon_La1(gds), 0.001*GDS_LatLon_La2(gds),
2022-12-19T18:36:32.0710428Z      ^
2022-12-19T18:36:32.0711873Z libbacktrace could not find executable to open
2022-12-19T18:36:32.0712700Z Please submit a full bug report,
```

**Comment by ocefpaf** [comment]
I'm OK skipping Windows BTW.

**Comment by akrherz** [comment]
anaconda.org reported download counts

Arch | Downloads
--- | ---
win-64/wgrib-1.8.1.2c-h301d43c_0.tar.bz2 | 1285 | 
osx-64/wgrib-1.8.1.2c-h01d97ff_0.tar.bz2 | 396 |
linux-64/wgrib-1.8.1.2c-h516909a_0.tar.bz2 | 5380 |

I'm fine with dropping windows. :)

**Comment by akrherz** [comment]
windows fails with
```
Mamba failed to solve:
 - m2w64_c_win-64
 - m2-make
with channels:

The reported errors are:
   - nothing provides requested m2w64_c_win-64
```

@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
> anaconda.org reported download counts

B/c wgrib is not used as a dependency anywhere those are probably real user and, 1285, is impressive for such a niche package. With that said, the previous build seems to be working on Windows and dropping here is not "never building it again", just waiting for someone who knows about Windows stuff to come along and help us fix it :-)

**Comment by akrherz** [comment]
@ocefpaf GREEN!  Thank you!

**Comment by ocefpaf** [comment]
I was going to add the basic shell utils on Windows but your solution is much better. Thanks!

**Pull request merged**
